Shipyard get action test
att-comdev/airship-tempest-plugin pull request #1
Opened 2018-09-19 10:58 UTC by rupamatt

Shipyard get action tests

2018-09-19 12:43 UTC, rb560u commented on airship_tempest_plugin/tests/api/shipyard/test_actions_ucp.py
> +        response, _ = self.shipyard_actions_client.get_action()
Without passing an action_id, I do not suspect that the response will be 200. Can you confirm?

2018-09-19 12:44 UTC, rb560u commented on airship_tempest_plugin/tests/api/shipyard/test_actions_ucp.py
> +        response, _ = self.shipyard_actions_client.get_action_validation()
Without passing an action_id and validation_id, I do not suspect that the response will be 200. Can you confirm?

2018-09-19 12:44 UTC, rb560u commented on airship_tempest_plugin/tests/api/shipyard/test_actions_ucp.py
> +        response, _ = self.shipyard_actions_client.get_action_step()
action_id and step_id likely needed for a successful 200 response

2018-09-19 12:47 UTC, rickbartra91 requested changes
As mentioned in the README:

DISCALIMER:
This initial implementation is just to meet the first use case which is RBAC testing. For RBAC testing, we only need to hit the API endpoint and check role permission to the API being tested. Some of the REST clients will need to be rewritten if functional testing is desired. 

In order to actually get a 200 response, I believe you need to provide valid arguments. Additionally, you may need to review the REST client to verify it is using the parameters correctly.

2018-10-01 09:40 UTC, closed without merging

2018-10-01 09:41 UTC, rupamatt commented
Started a new pull request for shipyard functional tests.